rancher-cifs volume driver for Azure file storage
rancher/storage pull request #53
Opened 2017-04-26 20:12 UTC by mfar-bcgdv

2017-04-26 20:21 UTC, mfar-bcgdv commented
https://github.com/rancher/rancher-catalog/pull/612

2017-06-30 21:30 UTC, deniseschannon commented
https://github.com/rancher/rancher/issues/9206

2017-07-06 23:57 UTC, LLParse requested changes

2017-07-06 23:57 UTC, LLParse commented on package/cifs/Dockerfile
> +    apt-get install -y jq curl nfs-common
I had to replace `nfs-common` with `cifs-utils` to get this to work.

2017-07-06 23:57 UTC, LLParse commented on package/cifs/rancher-cifs
> +#!/bin/bash
Can you please add executable permissions (`chmod +x`) to this file?

2017-07-26 20:02 UTC, mfar-bcgdv commented on package/cifs/Dockerfile
> +    apt-get install -y jq curl nfs-common
hi @LLParse ,
I added `cifs-utils` to my Dockerfile based on Microsoft instructions:
https://docs.microsoft.com/en-us/azure/storage/storage-how-to-use-files-linux
This image been in use on some of our prod environments for couple months now without any hiccups.
let me know if you still wanna replace that package.

2017-07-26 20:09 UTC, mfar-bcgdv commented on package/cifs/rancher-cifs
> +#!/bin/bash
done :)

2017-07-26 20:15 UTC, LLParse commented on package/cifs/Dockerfile
> +    apt-get install -y jq curl nfs-common
To make sure I'm on the same page, you installed `cifs-utils` package on the host and the storage plugin functions, correct?

We typically try to ship all dependencies within the Docker image so the user doesn't need to perform any manual setup on the underlying hosts. In some scenarios (RancherOS, Atomic), installing deps on the host is not even possible. I would like to see the package added, thanks.

cc @moelsayed

2017-07-26 20:22 UTC, LLParse commented on package/cifs/rancher-cifs
> +#!/bin/bash
Thanks!

2017-07-26 20:51 UTC, mfar-bcgdv commented on package/cifs/Dockerfile
> +    apt-get install -y jq curl nfs-common
I used ubuntu vanilla 16:04 as my VM os & did not install any packages in os level.
Maybe `nfs-common` is already preinstalled in ubuntu 16.04.
lets add both of these packages in Dockerfile, agreed?

2017-07-26 21:50 UTC, LLParse commented on package/cifs/Dockerfile
> +    apt-get install -y jq curl nfs-common
:+1:

2017-07-26 23:00 UTC, mfar-bcgdv commented on package/cifs/Dockerfile
> +    apt-get install -y jq curl nfs-common
done.

2017-09-01 09:17 UTC, richbayliss commented
Can we expect official CIFS support in the next release?

2017-09-01 16:18 UTC, LLParse commented
@moelsayed  ^^

2017-12-01 11:40 UTC, richbayliss commented
Is there any update on this one?

2018-03-03 08:38 UTC, annerajb commented
Is this project dead?

2018-06-18 17:14 UTC, deniseschannon commented
We've moved from using docker volumes to flex volumes. If this PR is re-worked to use flexvolumes, we can look to review and merge it in. 

PRs that were done for other storage drivers that moved to using flex volumes:
* https://github.com/rancher/storage/pull/58
* https://github.com/rancher/storage/pull/80
* https://github.com/rancher/agent/pull/229
* https://github.com/rancher/cattle/pull/2906

2020-08-01 04:02 UTC, cjellick commented
Closing this due to staleness. Feel free to reopen or open a new PR if there's still a relevant change to be made. Thanks!

2020-08-01 04:02 UTC, closed without merging