Add storage for Aliyun Block Storage
rancher/storage pull request #65
Opened 2017-08-10 04:57 UTC by thxCode

2017-08-11 06:17 UTC, zionwu commented
rancher/rancher#9194

2017-08-11 06:51 UTC, yasker requested changes
I will review more after these comments are addressed.

2017-08-11 06:51 UTC, yasker commented on package/abs/Dockerfile
> +# COPY abs/aliyun.list /etc/apt/sources.list.d/
Commented out? Then why do we need `aliyun.list`?

2017-08-11 06:51 UTC, yasker commented on package/abs/Dockerfile
> +# Set the base image to Ubuntu 16.04
It's too obvious, you don't need to comment.

2017-08-11 06:51 UTC, yasker commented on package/abs/Dockerfile
> +# Update repo
Same here, and all the followings..

2017-08-11 06:51 UTC, yasker commented on package/abs/aliyun.list
> +# deb cdrom:[Ubuntu 16.04 LTS _Xenial Xerus_ - Release amd64 (20160420.1)]/ xenial main restricted
Don't know if we still need this due to the commented out part in Dockerfile.

2017-08-11 06:51 UTC, yasker commented on package/abs/rancher-abs
> +readonly ACCESS_KEY_ID=${ECS_ACCESS_KEY_ID}
What's this `ECS_ACCESS_KEY_ID` and `SECRET`? I didn't see it mentioned anywhere.

2017-08-11 06:51 UTC, yasker commented on package/abs/rancher-abs
> +LOG() {
Don't use upper case function names. You can refer to https://google.github.io/styleguide/shell.xml

2017-08-11 06:51 UTC, yasker commented on package/abs/rancher-abs
> +# Gen clientToken
Too obvious.

2017-08-11 06:51 UTC, yasker commented on package/abs/rancher-abs
> +# Gen diskName
Comments are too obvious. Let code speak for itself. Don't add comments unless necessary.

2017-08-11 06:51 UTC, yasker commented on package/abs/rancher-abs
> +# Find avaiable device path in os, sush as '/dev/vdb', '/dev/vdc',..., '/dev/vdz'
Typo. `such`, not `sush`

2017-08-11 06:51 UTC, yasker commented on package/abs/rancher-abs
> +    local aliyun_options="--ZoneId ${zone_id} --DiskName ${disk_name} --Size ${size} --DiskCategory ${disk_category}"
Inconsistent style. For `zone_id` you separated the define and assignment. Here you define it locally. You should stick to one style. Define it when using is fine with bash.

2017-08-11 07:07 UTC, thxCode commented on package/abs/Dockerfile
> +# COPY abs/aliyun.list /etc/apt/sources.list.d/
I forget to delete it. This file can help me to improve the speed when updating Ubuntu at home.

2017-08-11 07:14 UTC, thxCode commented on package/abs/rancher-abs
> +readonly ACCESS_KEY_ID=${ECS_ACCESS_KEY_ID}
They come from [catalog](https://github.com/thxCode/rancher-catalog/blob/04d993a6141097a3f8cf8e8879876b69e185be36/infra-templates/abs/0/docker-compose.yml#L12).

2017-08-11 07:15 UTC, thxCode commented on package/abs/rancher-abs
> +LOG() {
OK, I get.

2017-08-11 18:00 UTC, yasker commented
Please squash the commits to make it easier to review and merge.

In general, commits should be separated in a logical way to help reviewer and a later developer to understand. In this case, one commit should be enough.

2017-08-22 19:30 UTC, yasker approved these changes

2017-08-22 19:31 UTC, yasker commented
Hi @cjellick 

Can you review this one?

Thanks!

2017-08-28 22:08 UTC, cjellick commented
LGTM. I just verified that the code can be merged without affecting api/existing functionality.

2017-08-28 22:10 UTC, merged